\documentclass{beamer}
\setbeamertemplate{navigation symbols}{}


\title{Microarray Analysis}
\author{}
\date{}

\begin{document}
<<set-options, echo=FALSE, cache=FALSE>>=
opts_chunk$set(echo = FALSE, fig.path = 'figure/', dev = 'pdf', fig.align='center', fig.show='hold')
read_chunk('1_load.R')
@

<<load>>=
@

<<ext_code1>>=
read_chunk('1.5_functions.R')
@

<<func1>>=
@

<<ext_code2>>=
read_chunk('2_clean.R')
@

<<clean>>=
@

<<ext_code3>>=
read_chunk('3_functions.R')
@

<<func2>>=
@

<<ext_code4>>=
read_chunk('4_do.R')
@

\begin{frame}
    \titlepage
\end{frame}

\section{Microarray Workflow}
    \subsection{Samples}
        \begin{frame}
            \begin{center}
                \includegraphics[height = 8cm]{Figure/samples_slide.pdf}
            \end{center}
        \end{frame}

% maybe change this bit into a single slide with a diagram?

    \subsection{Microarrays}
        \begin{frame}
            % Single channel Agilent microarray (or at least the data was collected using an agilent thing anyway)
            % to compare between arrays in the experiment normalised to 75th percentile and RMA
        \end{frame}
    
    \subsection{Data}
        \begin{frame}
            % I was given data based on the RNAseq experiments by Nick and Brian Lam
            % this was being used to look at expression differences between 
            % contigs that Brian made 
        \end{frame}
        
    \subsection{What I did}
        \begin{frame}
            % I also had the sequences of the contigs so I blasted the 
            % contigs against the mito
            % genome and used the contigs that had a perfect match to Eurydice 
            % genome as markers
            % of mitochondrial gene expression
        \end{frame}
        
\section{Graphs}
    \begin{frame}
        % whole timcourse plot
    \end{frame}
    
    \subsection{Circadian}
        \begin{frame}
            % whole circadian
        \end{frame}
        \begin{frame}
            % significant circadian
        \end{frame}    
    
    \subsection{tidal}
        \begin{frame}
            % whole tidal
        \end{frame}
        \begin{frame}
            % significant tidal
        \end{frame}        
    
    \begin{frame}
        % session info
    \end{frame}

\section{what I intend to do}
    \begin{frame}
        % now I have the probe sequences and raw data so I will do shit with them
    \end{frame}
    
\section{Immuno}
    \begin{frame}
        % pretty picture time
    \end{frame}

\end{document}